
project_id = "zdpileidtdzlambmbsiq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.paypal-subscription]
verify_jwt = true
