// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdpileidtdzlambmbsiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcGlsZWlkdGR6bGFtYm1ic2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTIxOTEsImV4cCI6MjA2MTE4ODE5MX0.Ot72J4IaH9mtAdPtmry5jyZsv-g5G-fiM-zn_t9QBjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);